name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - uses: actions/checkout@v3
        with:
          clean: 'false'

      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm

      - run: npm install
      - run: npm run dev
